# To be built
LOCAL_TARGET    =  test1
LOCAL_SOTARGET  = 
LOCAL_OBJS      = test1.o

# Control.
LOCAL_LIBS      = -lrows
LOCAL_LIBPATH   = -L$(PROJECT_ROOT)/artefacts/lib
LOCAL_INCPATH   = -I$(PROJECT_ROOT)/cpp-includes
LOCAL_DEFINES   =
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  = -O3
LOCAL_LDFLAGS   = 
LOCAL_LDSOFLAGS =

include $(PROJECT_ROOT)/env/makerules/build.rules
