# To be built
LOCAL_TARGET    =  
LOCAL_SOTARGET  = $(PROJECT_ROOT)/artefacts/lib/librows.so
LOCAL_OBJS      = csv.o

# Control.
LOCAL_LIBS      = 
LOCAL_LIBPATH   = 
LOCAL_INCPATH   = -I$(PROJECT_ROOT)/cpp-includes
LOCAL_DEFINES   =
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  = -O3
LOCAL_LDFLAGS   = 
LOCAL_LDSOFLAGS =

include $(PROJECT_ROOT)/env/makerules/build.rules
